---
- username: alex@library.ucsb.edu
  password: 'cats?'
  groups:
    - META_ADMIN
    - RIGHTS_ADMIN
    - UCSB_GROUP

- username: meta@library.ucsb.edu
  password: metadatum
  groups:
    - META_ADMIN
    - UCSB_GROUP

- username: rights@library.ucsb.edu
  password: righteous
  groups:
    - RIGHTS_ADMIN
    - UCSB_GROUP
