Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
