inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/*~'
    - 'db/**/*'
    - 'tmp/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/For:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/Lambda:
  EnforcedStyle: lambda

# RSpec's `include` method causes this to false-positive
Style/MixinGrouping:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
