language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2
before_script:
  - "cp config/secrets.yml.template config/secrets.yml"

notifications:
  email:
    - justin@curationexperts.com

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
