---
sudo: false
language: ruby

notifications:
  email: false

rvm:
  - 2.3.1
  - 2.4.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=1
    - CI=1

cache:
  bundler: true

jdk:
  - oraclejdk8

before_script:
  - cp config/secrets.yml.template config/secrets.yml
