defaults: &defaults
  derivatives_dir: <%= ENV['ADRL_DERIVATIVES'] || "tmp/derivatives" %>
  download_root: <%= ENV['ADRL_DOWNLOAD_ROOT'] || "tmp/download_root" %>
  ezid_host: ezid.cdlib.org
  ezid_port: 443
  internal_local_vocab_root: http://<%= Rails.application.config.host_name %>
  localhost_port: 3000
  marmotta_host: localhost:8080
  minter_state: <%= ENV['ADRL_MINTER_STATE'] || "tmp/minter-state" %>
  uploads_dir: <%= ENV['ADRL_UPLOADS'] || "tmp/uploads" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  derivatives_dir: /opt/alexandria/derivatives
  download_root: /opt/download_root
  internal_local_vocab_root: 'http://alexandria.ucsb.edu:8080/fedora/rest'
  internal_local_vocab_root: http://<%= Rails.application.config.host_name %>
  marmotta_host: <%= Rails.application.config.host_name %>:8080
  minter_state: /opt/alexandria/shared/minter-state
  uploads_dir: /opt/alexandria/uploads
