defaults: &defaults
  adapter: solr

development:
  <<: *defaults
  url: <%= ENV['DEV_SOLR_URL'] || 'http://localhost:8985/solr/development' %>

test:
  <<: *defaults
  url: <%= ENV['TEST_SOLR_URL'] || 'http://localhost:8985/solr/test' %>

production:
  <<: *defaults
  url: 'http://localhost:8983/solr/collection1'
