defaults: &defaults
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

development:
  <<: *defaults

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *defaults
  host: <%= Rails.application.secrets.psql_host %>
