defaults: &defaults
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3

production:
  <<: *defaults
  adapter: postgresql
  database: <%= Rails.application.secrets.hydra_postgres_db %>
  host: <%= Rails.application.secrets.psql_host %>
  password: <%= Rails.application.secrets.hydra_postgres_pass %>
  username: <%= Rails.application.secrets.hydra_postgres_user %>
