defaults: &defaults
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3

production:
  <<: *defaults
  adapter: postgresql
  database: "<%= SS.get_secret(SS::PSQL_SECRET_ID, 'Resource') %>"
  host: <%= Rails.application.secrets.psql_host %>
  password: "<%= SS.get_secret(SS::PSQL_SECRET_ID, 'Password') %>"
  username: "<%= SS.get_secret(SS::PSQL_SECRET_ID, 'Username') %>"
