defaults: &defaults
  adapter: postgresql
  encoding: unicode
  password: <%= Rails.application.secrets.hydra_postgres_pass %>
  pool: 5
  username: <%= Rails.application.secrets.hydra_postgres_user %>
  host: localhost

development:
  <<: *defaults
  database: <%= Rails.application.secrets.hydra_postgres_db %>

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *defaults
  database: <%= Rails.application.secrets.hydra_postgres_db %>
  username: <%= Rails.application.secrets.hydra_postgres_user %>
