defaults: &defaults
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3

production:
  <<: *defaults
  adapter: postgresql
  database: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s #{PSQL_SECRET_ID} Resource`.strip } %>"
  host: <%= Rails.application.secrets.psql_host %>
  password: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s #{PSQL_SECRET_ID} Password`.strip } %>"
  username: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s #{PSQL_SECRET_ID} Username`.strip } %>"
