defaults: &defaults
  adapter: postgresql
  database: <%= Rails.application.secrets.hydra_postgres_db %>
  encoding: unicode
  host: 127.0.0.1
  password: <%= Rails.application.secrets.hydra_postgres_pass %>
  pool: 5
  username: <%= Rails.application.secrets.hydra_postgres_user %>

development:
  <<: *defaults

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *defaults
