default: &default
  shoulder: ark:/99999/fk4
  password: "<%= Rails.application.secrets.ezid_test_pass %>"
  username: apitest

development:
  <<: *default

test:
  <<: *default

production:
  shoulder: ark:/48907/f3
  password: "<%= SS.get_secret(391, 'Password') %>"
  username: "<%= SS.get_secret(391, 'Username') %>"
