defaults: &defaults
  password: <%= Rails.application.secrets.fedora_pass %>
  url: http://127.0.0.1:<%= ENV['TEST_JETTY_PORT'] || 8080 %>/fedora/rest
  user: fedoraAdmin

development:
  <<: *defaults
  base_path: /devel

test:
  <<: *defaults
  base_path: /test
  url: http://127.0.0.1:<%= ENV['TEST_JETTY_PORT'] || 8983 %>/fedora/rest

production:
  <<: *defaults
  base_path: /prod
