ucsb:
  production:
    admin_pass: "<%= SS.get_secret(49, 'Password') %>"
    admin_user: "<%= SS.get_secret(49, 'Username') %>"
    attribute: uid
    filter: uid
    group_base: "ou=People,o=ucsb"
    host: "<%= SS.get_secret(49, 'Resource') %>"
    port: 636
    ssl: true

staff:
  production:
    admin_pass: "<%= SS.get_secret(1331, 'Password') %>"
    admin_user: "<%= SS.get_secret(1331, 'Username') %>"
    filter: userprincipalname
    group_base: "dc=library,dc=ucsb,dc=edu"
    host: "<%= SS.get_secret(1331, 'Domain') %>"
    port: 636
    ssl: true
