ucsb:
  production:
    admin_pass: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s 49 Password`.strip } %>"
    admin_user: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s 49 Username`.strip } %>"
    attribute: uid
    filter: uid
    group_base: "ou=People,o=ucsb"
    host: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s 49 Resource`.strip } %>"
    port: 636
    ssl: true

staff:
  production:
    admin_pass: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s 1331 Password`.strip } %>"
    admin_user: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s 1331 Username`.strip } %>"
    filter: userprincipalname
    group_base: "dc=library,dc=ucsb,dc=edu"
    host: "<%= Dir.chdir('/opt/secret-server') { `java -jar secretserver-jconsole.jar -s 1331 Domain`.strip } %>"
    port: 636
    ssl: true
