development:
  url: <%= ENV['DEV_SOLR_URL'] || 'http://localhost:8983/solr/development' %>

test:
  url: <%= ENV['TEST_SOLR_URL'] || 'http://localhost:8985/solr/test' %>

production:
  url: <%= "http://#{Rails.application.secrets.solr_host}:8983/solr/collection1" %>
