---
- name: write ADRL settings to application.yml
  become: yes
  lineinfile:
      backup: yes
      dest: "{{ config_path }}/application.yml"
      state: present
      insertafter: ^default
      line: "{{ item }}"
  with_items:
    - "  download_root: {{ etd_download_root }}"
    - "  internal_local_vocab_root: 'http://alexandria.ucsb.edu:8080/fedora/rest'"
    - "  marmotta_host: {{ server_name }}:8080"
    - "  minter_state: {{ minter_state_location }}"

- name: write ADRL test settings to application.yml
  become: yes
  lineinfile:
      backup: yes
      dest: "{{ config_path }}/application.yml"
      state: present
      insertafter: ^test
      line: "{{ item }}"
  with_items:
    - "  marmotta_host: localhost:8180"
